allowBuilds:
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
minimumReleaseAgeExclude:
  - '@types/node@26.5.1'
  - autoprefixer@10.5.6
overrides:
  vite: 'catalog:'
  postcss: ^8.5.28
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
